COPY ~%MOD_FOLDER%/Elementalist/2da~ ~override~
COPY ~%MOD_FOLDER%/Elementalist/spells~ ~override~

ADD_KIT ~C0ELEM~

 // appended to CLASWEAP.2da
 ~C0ELEM		1           1           1           1           1           1           1           1~

 // appended column-wise to WEAPPROF.2da
//11                                T   S           F   Q             S S
//10                                W   C           L   U             W I
//9                         B L S   O   I   W       A   A             O N
//8                         A O H   H   M   A       I   R C   S       R G
//7         L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         _ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2         R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1         D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~C0ELEM	1 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
    
 // appended to ABCLASRQ.2da
 ~C0ELEM				0      0	0	0	12	15~

 // appended to ABCLSMOD.2da
 ~C0ELEM				0	0	0	0	0	0~

 // appended to ABDCDSRQ.2da
 ~C0ELEM                		0       0       0       0       17       17~

 // appended to ABDCSCRQ.2da
 ~C0ELEM                 	0       0       0       0       15		15~

 // appended to ALIGNMNT.2da	LG	LN	LE	NG	TN	NE	CG	CN	CE 
 ~C0ELEM                  		0	0	0	0	1	0	0	0	0~

 // appended to DUALCLAS.2da
 ~C0ELEM                  	1       0       0       0       0       0~

 // path to your CLAB-style 2da file 
 ~%MOD_FOLDER%/Elementalist/2da/C0ELEM.2da~

 // PC races and classes allowed to use this kit, from KITTABLE.2da
 ~K_D_H K_D_E K_D_HE K_D_HL K_D_D K_D_G K_D_HO~

 // usability flags, added to the end of the KITLIST.2da entry
 ~0x10000000     11~

 // HLA table to use; see LUABBR.2da
 ~DR0~

 // list of starting equipment for PCs starting in ToB. Appended column-wise to 25STWEAP.2da
 ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~

 // Lower, mixed, and help kit names and descriptions, added to KITLIST.2da
  SAY ~elementalist~
  SAY ~Elementalist~
  SAY ~^0xFF12B4E6ELEMENTALIST:^- Elementalist druids specialize in the natural energies of Nature, allowing them to command the elements with exceptional skill.

^0xFF12B4E6Advantages:^-
– +20% resistance to acid, cold, electrical and fire damage.
– +20% to acid, cold, electrical and fire damage dealt.
– Two arcane spells per spell level are added to <PRO_HISHER> repertoire, all the way up to the 7th level. These are listed below:
  1st level: Burning Hands, Shocking Grasp
  2nd level: Agannazar's Scorcher, Melf's Acid Arrow
  3rd level: Fireball, Lightning Bolt
  4th level: Fire Shield (Red), Ice Storm
  5th level: Cone of Cold, Sunfire
  6th level: Chain Lightning, Death Fog
  7th level: Protection from the Elements, Acid Storm

^0xFF12B4E6Disadvantages:^-
– May not wear any armor.
– May not cast any spells of the Animal and non-Elemental Summoning Spheres.
– May not shapeshift into any animal forms.~

LAF fl#add_kit_ee
  STR_VAR
    kit_name = C0ELEM
	hpclass = ~HPPRS~
END

COPY_EXISTING ~SPWI103.spl~ ~override/C0EL103.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI115.spl~ ~override/C0EL115.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI211.spl~ ~override/C0EL211.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI217.spl~ ~override/C0EL217.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI304.spl~ ~override/C0EL304.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI308.spl~ ~override/C0EL308.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI404.spl~ ~override/C0EL404.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI418.spl~ ~override/C0EL418.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI503.spl~ ~override/C0EL503.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI523.spl~ ~override/C0EL523.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI614.spl~ ~override/C0EL614.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI615.spl~ ~override/C0EL615.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI702.spl~ ~override/C0EL702.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI712.spl~ ~override/C0EL712.spl~
WRITE_SHORT 0x1C 2 
ACTION_IF FILE_EXISTS_IN_GAME ~SPWI724.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI724.spl~ ~override/C0EL724.spl~
WRITE_SHORT 0x1C 2 
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI724.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Elementalist/acidstorm/astorma.bam~ ~override~
COPY ~%MOD_FOLDER%/Elementalist/acidstorm/astormx.bam~ ~override~
COPY ~%MOD_FOLDER%/Elementalist/acidstorm/spwi724.spl~ ~override~
SAY NAME1 ~Acid Storm~
SAY UNIDENTIFIED_DESC ~Acid Storm
(Evocation)

Level: 7
Range: Visual range of the caster
Duration: 1 round/level
Casting Time: 7
Area of Effect: 12-ft. radius
Saving Throw: 1/2

This spell unleashes an acidic downpour on the area of effect, doing 1d4 points of acid damage each round for the first three rounds, 1d6 points for the next three rounds, and 1d8 points for each round thereafter. Moving out of the area of effect does not stop the damage—the acid adheres to the skin, and any creatures in the area of effect when Acid Storm is cast continue to suffer acid damage as long as the spell duration lasts. Creatures make a Save vs. Spell every round after they have been hit by the cloud—if successful, they only take half damage (for that round only).~
COPY ~%MOD_FOLDER%/Elementalist/acidstorm/spwi724b.bam~ ~override~
COPY ~%MOD_FOLDER%/Elementalist/acidstorm/spwi724c.bam~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Elementalist/acidstorm/IDPRO211.PRO~
END

LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR204~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~ kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR305~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR319~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR402~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR410~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
ACTION_IF FILE_EXISTS ~sppr418.spl~ THEN BEGIN
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR418~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR501~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR517~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR602~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR604~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~SPPR717~ class_include=~{'DRUID_ALL', 'RANGER_ALL', }~  kit_exclude=~{'C0ELEM', }~ END

LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL103~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL115~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL211~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL217~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL304~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL308~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL404~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL418~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL503~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL523~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL614~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL615~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL702~  kit_include=~{'C0ELEM', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0EL712~  kit_include=~{'C0ELEM', }~ END