COPY ~%MOD_FOLDER%/MonkRevision/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/audio~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/bam~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/bmp~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/eff~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/fists~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/items~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/spells/strength_exceptional~ ~OVERRIDE~
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 20) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0MN#04 END // FLURRY OF BLOWS
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0AK#EX END // FLURRY OF BLOWS
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 8 STR_VAR f_Entry = AP_C0MN#04Z END // FLURRY OF BLOWS
        PRETTY_PRINT_2DA

      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "C0_BRAWLER")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0MN#13 END // FLURRY OF BLOWS
        PRETTY_PRINT_2DA
      END
	  
      BUT_ONLY
      END
    END
  END
  END

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    BGCLATXT  
    clastext  
    sodcltxt 
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//BRAWLER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "C0_BRAWLER" BEGIN
          READ_2DA_ENTRY index 4 col_count brawler_desc
          SPRINT old_brawler_1 ~– May not use Lay on Hands.~
          SPRINT new_brawler_1 ~– May not use Wholeness of Body.~
          SPRINT old_brawler_2 ~– Does not gain Magic Resistance.
– Does not gain immunity to disease, slow, haste, charm, poison or non-magical weapons.~
          SPRINT new_brawler_2 ~– Does not gain Wisdom bonuses to Armor Class.
– Does not gain Still Mind, Purity of Body, Diamond Body, Diamond Soul or Perfect Self.~
          GET_STRREF %brawler_desc% brawler_text
          INNER_PATCH_SAVE brawler_text ~%brawler_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_brawler_1%~ ~%new_brawler_1%~
            REPLACE_TEXTUALLY ~%old_brawler_2%~ ~%new_brawler_2%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%brawler_desc%~ ~%brawler_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
//ENABLE MONK FOR HALFORCS___________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 54 1 8 ~1~
		SET_2DA_ENTRY 54 3 8 ~1~
		SET_2DA_ENTRY 54 7 8 ~1~
		SET_2DA_ENTRY 56 1 8 ~1~
		SET_2DA_ENTRY 56 3 8 ~1~
		SET_2DA_ENTRY 56 7 8 ~1~
		SET_2DA_ENTRY 57 1 8 ~1~
		SET_2DA_ENTRY 57 3 8 ~1~
		SET_2DA_ENTRY 57 7 8 ~1~
	BUT_ONLY
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~K_MN_HO.2DA~ THEN BEGIN
COPY ~%MOD_FOLDER%/MonkRevision/K_MN_HO~ OVERRIDE
END

ACTION_IF FILE_EXISTS_IN_GAME ~K_MN_HO.2DA~ THEN BEGIN
APPEND ~K_MN_HO.2DA~ ~2    36
3    37~ UNLESS ~2    36~
END

ACTION_FOR_EACH monk_avatar IN 6500 6510 6505 6515 BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%monk_avatar%.ini~ THEN BEGIN
COPY_EXISTING ~%monk_avatar%.ini~   ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~equip_helmet=1~~~~~
    string = EVAL ~~~~~equip_helmet=0~~~~~ //"
  END
  END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY monk_anims_6xxx BEGIN
    ~6500~ => ~MONK_MALE_HUMAN_1~
    ~6500a~ => ~MONK_MALE_HUMAN_2~
    ~6505~ => ~MONK_MALE_HALFORC_1~
    ~6505a~ => ~MONK_MALE_HALFORC_2~
    ~6510~ => ~MONK_FEMALE_HUMAN_1~
    ~6510a~ => ~MONK_FEMALE_HUMAN_2~
    ~6515~ => ~MONK_FEMALE_HALFORC_1~
    ~6515a~ => ~MONK_FEMALE_HALFORC_2~
  END
  ACTION_PHP_EACH monk_anims_6xxx AS animation => symbol BEGIN
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x6000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/MonkRevision\animations\%animation%.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY halforc_monk_anims_6xxx BEGIN
    ~female~ => ~MONK_FEMALE_HALFORC~
    ~male~ => ~MONK_MALE_HALFORC~
  END
  ACTION_PHP_EACH halforc_monk_anims_6xxx AS folder => symbol BEGIN
    ACTION_BASH_FOR ~%MOD_FOLDER%/MonkRevision\animations\halforc\%folder%~ ~.+\.bam~ ~%MOD_FOLDER%/MonkRevision\animations\halforc\%folder%~ ~.+\.bmp~ BEGIN
      COPY ~%BASH_FOR_FILESPEC%~ ~override~
    END
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x6000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/MonkRevision\animations\halforc\female/6515.ini~ ~override/6515.ini~
    COPY ~%MOD_FOLDER%/MonkRevision\animations\halforc\male/6505.ini~ ~override/6505.ini~
    COPY_EXISTING ~6500.ini~ ~override/6501.ini~
    COPY_EXISTING ~6510.ini~ ~override/6511.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x6501 MONK_MALE_ELF~
    APPEND ~ANIMATE.IDS~ ~0x6505 MONK_MALE_HALFORC~
    APPEND ~ANIMATE.IDS~ ~0x6511 MONK_MALE_ELF~
    APPEND ~ANIMATE.IDS~ ~0x6515 MONK_FEMALE_HALFORC~
END

// WISDOM
APPEND ~splprot.2da~ ~C0HTWIS 39 -1 1~ UNLESS ~C0HTWIS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTWIS~ BEGIN
	    SET C0HTWIS = %row%
	  END
	END
COPY ~%MOD_FOLDER%/MonkRevision/spells~ ~OVERRIDE~
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 326
			match_special = 1000
			parameter2 = C0HTWIS
			silent = 1
	END

DEFINE_ACTION_FUNCTION mod_monk_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  monk

	BEGIN
		OUTER_SPRINT $monks("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 2; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 20 BEGIN // monk
				SPRINT $monks("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH monks AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER wweapprof 34 (col + 1) 1
					SET_2DA_ENTRY_LATER wweapprof 34 58 3
					SET_2DA_ENTRY_LATER wweapprof 18 58 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW wweapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_monk_profs END

INCLUDE ~%MOD_FOLDER%/lib/monk_staves.tpa~

ACTION_FOR_EACH CLASSTEXT IN CLASTEXT SODCLTXT BEGIN
ACTION_IF (FILE_EXISTS_IN_GAME ~%CLASSTEXT%.2da~) BEGIN
  COPY_EXISTING ~%CLASSTEXT%.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (~MONK: Monks are warriors who pursue perfection through contemplation as well as action. They are versatile fighters, especially skilled in combat without weapons or armor. Though Monks cannot cast spells, they have a unique magic of their own: They channel a subtle energy, called ki, which allows them to perform amazing feats. The Monk's best known feat is their ability to stun an opponent with an unarmed blow.

CLASS FEATURES:

– May not wear any armor.
– May only use weapons available to the Thief class.
– May achieve Grandmastery (five slots) in Quarterstaves.
– May only become Proficient (one slot) in any weapon class.
– May become Proficient (one slot) in Two-Handed Weapon Style, Single-Weapon Style and Two-Weapon Style.
– May use the Hide In Shadows and Find Trap abilities (but may not disarm traps)
– Moves 2 points faster than other characters. Movement rate further improves by 1 every 5 levels.
– May make 2 attacks per round while unarmed or when wielding a quarterstaff.
– -1 to Speed Factor per 3 levels.

– Flurry of Blows: The monk, while unarmed or wielding daggers, may make an additional attack at the same time as their first attack each round at the cost of a -5 penalty to THAC0. This extra attack is not subject to the attacks per round limit and may be toggled at will. THAC0 penalty decreases to -2 at 13th level.

– The monk's fists deal crushing damage and deal increase damage with level as follows:
  Level 1-2: 1d4
  Level 3-4: 1d6
  Level 5-6: 1d8
  Level 7-9: 1d10
  Level 10-14: 1d12
  Level 15-19: 2d8
  Level 20-24: 2d10
  Level 25+: 2d12
  
– Ki: The monk's unarmed attacks are empowered with ki, which allows them to be treated as magical weapons of +1 enchantment at 4th level, +2 at 8th level, +3 at 12th level, +4 at 16th level and +5 at 20th level. From 7th level, they are treated as silver weapons.
– Receives a +1 bonus to all Saving Throws. An additional +1 is gained at 5th level and every 5 levels thereafter.
– The monk gains a +1 bonus to base Armor Class per point of Wisdom above 12. They gain an additional +1 to AC at 5th level and every 5 levels thereafter.
– Deflect Missiles: The monk receives a +1 bonus to AC vs. missile attacks every 3 levels.
– May use the Stunning Blow ability once per day. Gains one use at level 1 and an additional use every 4 levels thereafter.

STUNNING BLOW: The monk sacrifices four points of THAC0 and damage for their next successful attack within 10 seconds. When struck, the target must make a Save vs. Death (-1 modifier per point of Wisdom above 14) or be stunned for three rounds.

– 3rd level: Still Mind: The monk receives a +2 bonus to Saving Throws vs. Enchantment spells.
– 5th level: Purity of Body: The monk gains permanent Free Action and immunity to all diseases.
– 7th level: May use Wholeness of Body once per day.

WHOLENESS OF BODY: The monk instantly heals themself for three hit points per monk level.

– 8th level: Greater Flurry: The monk now makes an additional second attack per round while Flurry of Blows is active.
– 11th level: Diamond Body: The monk permanently becomes immune to poison.
– 12th level: Diamond Soul: The monk gains base 10% + 2% Magic Resistance per monk level up to a maximum of 70% at 30th level.
– 13th level: May use the Quivering Palm ability once per day.

QUIVERING PALM: The most advanced of the monk's techniques. When used, the monk's next successful attack within 10 seconds sets up fatal vibrations within the target's body, instantly killing them unless a successful Save vs. Death (-1 modifier per point of Wisdom above 16) is made.

– 14th level: May use Empty Body twice per day.

EMPTY BODY: The monk gains the ability to fade from sight, granting them partial invisibility for one round per level. Attacks against the monk suffer a -4 penalty to attack rolls, and the monk's Saving Throws are made with a +4 bonus. The monk also cannot be targeted by spells from creatures unless they can see through invisibility.

– 15th level: Inner Eye: The monk becomes immune to critical hits while unarmed.
– 20th level: Perfect Self: The monk gains permanent immunity to Charm, Domination, Command, Sleep, Maze, Imprisonment, Confusion, Psionics and all weapons of +1 enchantment and below.
– Alignment restricted to lawful.
– Hit Die: d8~)
	  END
	END
  BUT_ONLY
	END
	END
  
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~DARK_MOON~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~DARK MOON MONK: The Order of the Dark Moon is a secretive monastic order that follows the teachings of the dark goddess Shar. Monks of the Dark Moon use physical prowess, dark magic, and many different forms of deception to mask their activities and strike with deadly precision.

Advantages:
– +10% to Detect Illusion.
– May invest points into the Detect Illusion skill.
– May achieve Mastery in Daggers.
– May place 3 slots into Two-Weapon Style.
– May use Sorcerous Lineage once per day. Gains extra uses at 6th and 12th levels.

SORCEROUS LINEAGE: Disciples of the Order of the Dark Moon must display some sort of sorcerous power during their initiation. As such, All Dark Moon Monks have a minor level of magical ability. This ability allows the Dark Moon Monk to cast a level 1 Invocation, Illusion or Necromancy spell of choice once per day. As the Dark Moon Monk gains in levels, stronger spells may be chosen, gaining level 2 spells at 5th level, level 3 spells at 9th level, level 4 spells at 13th level and level 5 spells at 17th level.

– 5th level: May cast Chilling Palm once per day.

CHILLING PALM: The Dark Moon Monk channels unearthly energy into their unarmed attacks, granting their fists an additional 1d4 magical cold damage (+1 per point of Wisdom above 14) for 1 round per 5 levels.

– 8th level: May cast Viperous Strike once per day. 

VIPEROUS STRIKE: The Dark Moon Monk strikes with a vicious blow that channels corruptive ki into their victim's body. Their next unarmed attack poisons the target. This poison deals damage and reduces the target's Constitution immediately and every following round for at least four rounds. After four rounds have passed, the target must make a Saving Throw vs. Death or remain poisoned for another four rounds. Therefore, the poison has the potential to last indefinitely as long as the target does not make a successful Saving Throw. The target may not die of Constitution loss caused by the poison.

1st level: Target suffers two poison damage and loses one point of Constitution. No save modifier.
6th level: Target suffers four poison damage and loses one point of Constitution. Save modifier of -1.
11th level: Target suffers six poison damage and loses two points of Constitution. Save modifier of -2.
16th level: Target suffers eight poison damage and loses two points of Constitution. Save modifier of -3.
21st level: Target suffers ten poison damage and loses three points of Constitution. Save modifier of -4.

– 13th level: May cast Crushing Darkness once per day.

CRUSHING DARKNESS: The Dark Moon Monk unleashes ki in a wave of psychic energy that assaults all creatures within a 15-ft. radius with an overwhelming despair, dealing 10d6 magical damage and draining them of two levels. For each target slain by this ability, the Dark Moon Monk is healed for 15% of their maximum hit points and temporarily gains +2 to THAC0 and Damage for six rounds.

– 17th level: May cast Eclipse once per day.

ECLIPSE: The Dark Moon Monk becomes wreathed in a cold shroud for one turn, gaining immunity to cold damage and +4 to Strength, Dexterity and Constitution. Any opponent who hits the Dark Moon Monk with any weapons or spells within this radius suffers 1d8+1 points of cold damage and must make a save vs. spells or be sapped, suffering an additional 1d6 magic damage and one point of THAC0 which is temporarily transferred to the Dark Moon Monk for two rounds.

– 20th level: Bringer of Despair: After casting Crushing Darkness, the Dark Moon Monk is empowered from the pain of their victims, gaining an additional +4 bonus to damage for three rounds. Additionally, killing any creature within the given three rounds grants the Dark Moon Monk the same effects as deaths caused by Crushing Darkness and refreshes the empowered duration.

Disadvantages:
– Alignment restricted to lawful evil.
– May not learn Solar or Storm Stance.
– May not use the Stunning Blow ability.
– May not use the Quivering Palm ability.
– May not use the Wholeness of Body ability.~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~SUN_SOUL~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~SUN SOUL MONK: Sun Soul Monks were once worshippers of Amaunator in the time of the Netheril, but today their worship is divided between Lathander, Selûne, and Sune. Sun Soul Monks adhere strictly to the law, using their martial arts and magical abilities to drive out darkness and corruption wherever they find it.

Advantages:
– Immune to Blindness and Level Drain.
– May cast Radiant Sunbolts once per day. Gains an extra use at 5th level and every 5 levels thereafter.

RADIANT SUNBOLTS: The Sun Soul Monk can create bolts of energy that flare with radiant light. These bolts can be thrown as a projectile with a +5 bonus to attack rolls. Each bolt deals 1d4+1 points of magical damage and 3 extra points of magical fire damage (10 against undead) and strike as +4 weapons. The Sun Soul Monk produces 5 missiles (+1 additional bolt per 5 monk levels) and may hurl up to five missiles per round.

– 5th level: May cast Blazing Fists once per day.

BLAZING FISTS: The Sun Soul Monk channels their inner light into their unarmed attacks, turning their fists into flaming weapons that deal an additional 1d4 magical fire damage (+1 per point of Wisdom above 14) for 1 round per 5 levels.

– 8th level: May cast Searing Arc Strike once per day.

SEARING ARC STRIKE: The Sun Soul Monk gathers ki within their fists and shapes them into searing waves of white-hot flames. The monk's next successful melee attack unleashes a 90-degree cone of flame which deals 5d6 magical fire damage and severely burns all targets, reducing their Armor Class, THAC0 and Damage by 4 points and dealing an additional 1d6 magical fire damage per round for one turn unless a successful Save vs. Spells is made. Additionally, all invisible targets lose their invisibility with no save.

– 13th level: May cast Searing Sunburst once per day.

SEARING SUNBURST: The Sun Soul Monk unleashes their ki in a massive pillar of light, dealing 10d6 magical damage to all enemies and blinding them for one round. Undead creatures must make a save vs. spells or be instantly destroyed.

– 17th level: May cast Solar Shield once per day.

SOLAR SHIELD: The Sun Soul Monk becomes wreathed in a luminous mantle, gaining immunity to fire damage and dealing 30% increased fire damage from all sources for 1 turn. Any opponent who hits the Sun Soul Monk with any weapons or spells within this radius suffers 1d8+1 points of magical fire damage and must make a save vs. spells or take an additional 1d8 magical fire damage and be blinded for one round.

– 20th level: Avatar of the Sun: After casting Searing Sunburst, the Sun Soul monk continues to radiate light for three rounds, gaining a +6 bonus to Armor Class and +30% bonus to resistance to slashing, piercing, crushing and missile damage. All enemies within 15-ft. of the Sun Soul monk take 1d6 magical damage each round and must make a save vs. spells at -2 or be blinded for one round.

Disadvantages:
– Alignment restricted to lawful good.
– May not learn Lunar or Shadow Stance.
– May not use Stunning Blow ability.
– May not use Quivering Palm ability.
– May not use Empty Body ability.~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Flurry of Blows~) STR_VAR bam_file = C0MN#04I RET C0MN#04I = icon END

COPY_EXISTING ~clswpbon.2da~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  FOR (row = 0; row < numRows; row += 1) BEGIN
    SET_2DA_ENTRY row 2 numCols ~0~
  END
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "DARK_MOON" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count (val+10)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~MFIST1.ITM~ OVERRIDE
SAY NAME1 ~Fist~
SAY NAME2 ~Fist~
COPY_EXISTING ~MFIST2.ITM~ OVERRIDE
SAY NAME1 ~Fist~
SAY NAME2 ~Fist~
COPY_EXISTING ~MFIST3.ITM~ OVERRIDE
SAY NAME1 ~Fist +1~
SAY NAME2 ~Fist +1~
COPY_EXISTING ~MFIST4.ITM~ OVERRIDE
SAY NAME1 ~Fist +1~
SAY NAME2 ~Fist +1~
COPY_EXISTING ~MFIST5.ITM~ OVERRIDE
SAY NAME1 ~Fist +1~
SAY NAME2 ~Fist +1~
COPY_EXISTING ~MFIST6.ITM~ OVERRIDE
SAY NAME1 ~Fist +2~
SAY NAME2 ~Fist +2~
COPY_EXISTING ~MFIST7.ITM~ OVERRIDE
SAY NAME1 ~Fist +2~
SAY NAME2 ~Fist +2~
COPY_EXISTING ~MFIST8.ITM~ OVERRIDE
SAY NAME1 ~Fist +3~
SAY NAME2 ~Fist +3~
COPY_EXISTING ~MFIST9.ITM~ OVERRIDE
SAY NAME1 ~Fist +3~
SAY NAME2 ~Fist +3~
COPY_EXISTING ~MFIST10.ITM~ OVERRIDE
SAY NAME1 ~Fist +4~
SAY NAME2 ~Fist +4~
COPY_EXISTING ~MFIST11.ITM~ OVERRIDE
SAY NAME1 ~Fist +5~
SAY NAME2 ~Fist +5~
COPY_EXISTING ~MFIST12.ITM~ OVERRIDE
SAY NAME1 ~Fist +5~
SAY NAME2 ~Fist +5~

COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HUMAN_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_BYTE 0x90 1
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#042.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HUMAN_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#042~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#043.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HUMAN_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#043~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#044.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HUMAN_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#044~

COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#045.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HALFORC_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#045~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#046.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HALFORC_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#046~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#047.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HALFORC_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#047~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#048.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HALFORC_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#048~

COPY_EXISTING ~C0MN#04.SPL~ OVERRIDE
SAY NAME1 ~Flurry of Blows~
SAY UNIDENTIFIED_DESC ~Flurry of Blows
The monk, while unarmed or wielding daggers, may make an additional attack at the same time as their first attack each round at the cost of a -5 penalty to THAC0. This extra attack is not subject to the attacks per round limit and may be toggled at will. THAC0 penalty decreases to -2 at 13th level.~

COPY_EXISTING ~C0MN#04B.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~Flurry of Blows Active~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0MN#04I END

COPY_EXISTING ~C0MN#04Z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~Flurry of Blows Inactive~) END

COPY_EXISTING ~C0MN#05.SPL~ OVERRIDE
SAY NAME1 ~Empty Body~
SAY UNIDENTIFIED_DESC ~Empty Body
The monk gains the ability to fade from sight, granting them partial invisibility for one round per level. Attacks against the monk suffer a -4 penalty to attack rolls, and the monk's Saving Throws are made with a +4 bonus. The monk also cannot be targeted by spells from creatures unless they can see through invisibility.~

COPY_EXISTING ~SPCL811.SPL~ OVERRIDE
SAY NAME1 ~Stunning Blow~
SAY UNIDENTIFIED_DESC ~Stunning Blow
The monk sacrifices four points of THAC0 and damage for their next successful attack within 10 seconds. When struck, the target must make a Save vs. Death (-1 modifier per point of Wisdom above 14) or be stunned for three rounds.~

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 8 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00B END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 7 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00C END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 6 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00D END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 5 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00E END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 4 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00F END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 3 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00G END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 2 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00H END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 1 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00I END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 0 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00J END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00K.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-1"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00K END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00L.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-2"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00L END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00M.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-3"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00M END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01B END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01C END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01D END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01E END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01F END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01G END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01H END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01I END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01J END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01K.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01K END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01L.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01L END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01M.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01M END

COPY_EXISTING ~C0MN#01Z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Stunned~) END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02B END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02C END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02D END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02E END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02F END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02G END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02H END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02I END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02J END

COPY_EXISTING ~SPCL815.SPL~ OVERRIDE
SAY NAME1 ~Wholeness of Body~
SAY UNIDENTIFIED_DESC ~Wholeness of Body
The monk instantly heals themselves for three hit points per monk level.~

COPY_EXISTING ~SPCL820.SPL~ OVERRIDE
SAY NAME1 ~Quivering Palm~
SAY UNIDENTIFIED_DESC ~Quivering Palm
The most advanced of the monk's techniques. When used, the monk's next successful attack within 10 seconds sets up fatal vibrations within the target's body, instantly killing them unless a successful Save vs. Death (-1 modifier per point of Wisdom above 16) is made.~

COPY_EXISTING ~SPCL821.SPL~ OVERRIDE
SAY NAME1 ~Perfect Self~

COPY_EXISTING ~C0MN#H01.SPL~ OVERRIDE
SAY NAME1 ~Solar Stance~
SAY UNIDENTIFIED_DESC ~Solar Stance
The monk harnesses their ki into a fiery blaze, unleashing a burst of white-hot flame. All targets within a 15-ft. radius of the monk suffer 1d8 crushing and 12d6 fire damage (Save vs. Spells for half) and are sent flying and briefly knocked unconscious. The monk is shrouded in flame afterwards, granting them 2d6+1 bonus fire damage on their unarmed attacks for five rounds. Attacks made towards the monk within a 5-ft. radius also inflict 2d6+1 fire damage to the attacker.

Only one Stance may be active at any given time. Using another Stance will override the effects of the precedent one.~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0mn#h1p.PRO~
COPY_EXISTING ~C0MN#H1A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0mn#h1p END

COPY_EXISTING ~C0MN#H02.SPL~ OVERRIDE
SAY NAME1 ~Lunar Stance~
SAY UNIDENTIFIED_DESC ~Lunar Stance
The monk unleashes their ki in an illuminating wave of moonlight. All enemies within vision range of the monk must make a Save vs. Death at -5 or be blinded for five rounds. Targets who make their save are still blinded for one round. The remnants of light cloak the monk afterward, making them appear blurred and translucent. The monk gains a +10 bonus to Armor Class vs. all weapon types and all Saving Throws, partial invisibility and +50% resistance to all damage for five rounds.

Only one Stance may be active at any given time. Using another Stance will override the effects of the precedent one.~

COPY_EXISTING ~C0MN#H03.SPL~ OVERRIDE
SAY NAME1 ~Shadow Stance~
SAY UNIDENTIFIED_DESC ~Shadow Stance
The monk channels their ki throughout their body, turning themself completely invisible and intangible for five rounds. In this state, the monk cannot be damaged or targeted, even by creatures that can see through invisibility. The monk's next attack removes them from their intangible state and strikes at a weak point, dealing damage as a backstab with a bonus multiplier of 3. The target also suffers 5d10 additional magical damage and has their Armor Class reduced by 10 for one turn.

Only one Stance may be active at any given time. Using another Stance will override the effects of the precedent one.~

COPY_EXISTING ~C0MN#H04.SPL~ OVERRIDE
SAY NAME1 ~Storm Stance~
SAY UNIDENTIFIED_DESC ~Storm Stance
The monk shapes their ki into mystical lightning, unleashing it in a devastating storm upon their foes. All enemies with a 15-ft. radius of the monk are struck with lightning, dealing 4d6 electrical damage. The lightning then chains to nearby foes, dealing an additional 2d6 electrical damage. For the next five rounds, the monk's unarmed attacks erupt with a cone of energy dealing 2d6 electrical damage and dispelling effects at the monk's level on all targets.

Only one Stance may be active at any given time. Using another Stance will override the effects of the precedent one.~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0mn#h4p.PRO~
COPY_EXISTING ~C0MN#H4A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0mn#h4p END

COPY_EXISTING ~C0MN#H05.SPL~ OVERRIDE
SAY NAME1 ~Dragon Fist~
SAY UNIDENTIFIED_DESC ~Dragon Fist
The monk channels a focused amount of ki into their fists, allowing them to strike unerringly for a limited time. With this ability, every attack roll while unarmed made in the next round is a natural 20, a critical hit.~

COPY_EXISTING ~C0MN#H06.SPL~ OVERRIDE
SAY NAME1 ~Tiger Strike~
SAY UNIDENTIFIED_DESC ~Tiger Strike
The monk prepares their ki for a mighty leaping strike that resembles the pounce of a tiger. The monk's next unarmed attack within one round is an automatic critical hit and knocks the target away, stunning them for three rounds. The monk's movement rate is doubled until the attack is spent.

Requires: Dragon Fist~

COPY_EXISTING ~C0MN#H07.SPL~ OVERRIDE
SAY NAME1 ~Thousand Hands~
SAY UNIDENTIFIED_DESC ~Thousand Hands
This ability allows the monk to unleash a blindingly fast barrage of unarmed blows faster than the eye can match. For the next two rounds, the monk's attacks per round while unarmed are set to 10.~

COPY_EXISTING ~C0MN#H08.SPL~ OVERRIDE
SAY NAME1 ~Faster than the Eye~
SAY UNIDENTIFIED_DESC ~Faster than the Eye
This ability allows the monk to use their ki to move to a specific point within view at a rate so fast, one could mistake them for teleporting. Once learned, this ability may be used an unlimited times per day.~

COPY_EXISTING ~C0MN#H15.SPL~ OVERRIDE
SAY NAME1 ~Path of the Grandmaster~
SAY UNIDENTIFIED_DESC ~Path of the Grandmaster
The monk has perfected the fundamentals of their technique, gaining access to an ultimate ability which is dictated by their moral alignment. Good-aligned monks learn Pacifying Palm, neutral-aligned monks learn Equilibrium Strike, and evil-aligned monks learn Hand of Murder.

Pacifying Palm
A technique intended to subdue rather than kill. The monk's next successful unarmed attack within 10 seconds disrupts the target's cognitive abilities briefly, rendering them unable to act as though under a Feeblemind spell for two rounds. After the duration is over, all damage dealt by the target for the next four rounds is reduced by 66%.

Equilibrium Strike
The monk channels his ki into an empowered attack that enforces a state of balance upon both themselves and the target. The monk's next successful unarmed attack within 10 seconds deals damage to both the monk and the target equal to half of their remaining hit points. This damage cannot be reduced by any means.

Hand of Murder
A brutal, specialized advancement of the Quivering Palm technique that can be mastered only by the truly heartless. The monk's next successful unarmed attack within 10 seconds forces the target to make a successful Save vs. Death (-1 modifier per point of Wisdom above 16) or die. The monk gains temporary hit points equal to the amount of hit points the target had remaining before death for one turn.~

COPY_EXISTING ~C0MN#H09.SPL~ OVERRIDE
SAY NAME1 ~Pacifying Palm~
SAY UNIDENTIFIED_DESC ~Pacifying Palm
A technique intended to subdue rather than kill. The monk's next successful unarmed attack within 10 seconds disrupts the target's cognitive abilities briefly, rendering them unable to act as though under a Feeblemind spell for two rounds. After the duration is over, all damage dealt by the target for the next four rounds is reduced by 66%.~

COPY_EXISTING ~C0MN#H10.SPL~ OVERRIDE
SAY NAME1 ~Equilibrium Strike~
SAY UNIDENTIFIED_DESC ~Equilibrium Strike
The monk channels his ki into an empowered attack that enforces a state of balance upon both themselves and the target. The monk's next successful unarmed attack within 10 seconds deals damage to both the monk and the target equal to half of their remaining hit points. This damage cannot be reduced by any means.~

COPY_EXISTING ~C0MN#H11.SPL~ OVERRIDE
SAY NAME1 ~Hand of Murder~
SAY UNIDENTIFIED_DESC ~Hand of Murder
A brutal, specialized advancement of the Quivering Palm technique that can be mastered only by the truly heartless. The monk's next successful unarmed attack within 10 seconds forces the target to make a successful Save vs. Death (-1 modifier per point of Wisdom above 16) or die. The monk gains temporary hit points equal to the amount of hit points the target had remaining before death for one turn.~

COPY_EXISTING ~C0MN#H12.SPL~ OVERRIDE
SAY NAME1 ~Improved Diamond Soul~
SAY UNIDENTIFIED_DESC ~Improved Diamond Soul
The monk's mastery of ki allows them to negate even the strongest of magical effects. Each time this ability is chosen, the monk permanently gains +10% Magic Resistance and +1 to Saving Throws.

Improved Diamond Soul may be taken up to a maximum of two times.~

COPY_EXISTING ~C0MN#H13.SPL~ OVERRIDE
SAY NAME1 ~Timeless Body~
SAY UNIDENTIFIED_DESC ~Timeless Body
The monk's ki has developed to such an advanced level that it has become capable of permanently sustaining them. With this ability, the monk effectively becomes a timeless being, requiring neither food nor rest. As a result, the monk's movement rate is doubled, they gain permanent Aura Cleansing, and they can no longer become fatigued.~

COPY_EXISTING ~C0MN#H14.SPL~ OVERRIDE
SAY NAME1 ~Extra Quivering Palm~
SAY UNIDENTIFIED_DESC ~Extra Quivering Palm
The monk gains an additional daily use of Quivering Palm. This ability may be taken up to three times.~

COPY_EXISTING ~C0DMM01.SPL~ OVERRIDE
SAY NAME1 ~Sorcerous Lineage~
SAY UNIDENTIFIED_DESC ~Sorcerous Lineage
Disciples of the Order of the Dark Moon must display some sort of sorcerous power during their initiation. As such, All Dark Moon Monks have a minor level of magical ability. This ability allows the Dark Moon Monk to cast a level 1 Invocation, Illusion or Necromancy spell of choice once per day. As the Dark Moon Monk gains in levels, stronger spells may be chosen, gaining level 2 spells at 5th level, level 3 spells at 9th level, level 4 spells at 13th level and level 5 spells at 17th level.~

COPY_EXISTING ~C0DMM02.SPL~ OVERRIDE
SAY NAME1 ~Chilling Palm~
SAY UNIDENTIFIED_DESC ~Chilling Palm
The Dark Moon Monk channels unearthly energy into their unarmed attacks, granting their fists an additional 1d4 cold damage (+1 per point of Wisdom above 14) for 1 round per 5 levels.~

COPY_EXISTING ~C0DMM03.SPL~ OVERRIDE
SAY NAME1 ~Viperous Strike~
SAY UNIDENTIFIED_DESC ~Viperous Strike
The Dark Moon Monk strikes with a vicious blow that channels corruptive ki into their victim's body. Their next unarmed attack poisons the target. This poison deals damage and reduces the target's Constitution immediately and every following round for at least four rounds. After four rounds have passed, the target must make a Saving Throw vs. Death or remain poisoned for another four rounds. Therefore, the poison has the potential to last indefinitely as long as the target does not make a successful Saving Throw. The target may not die of Constitution loss caused by the poison.

1st level: Target suffers two poison damage and loses one point of Constitution. No save modifier.
6th level: Target suffers four poison damage and loses one point of Constitution. Save modifier of -1.
11th level: Target suffers six poison damage and loses two points of Constitution. Save modifier of -2.
16th level: Target suffers eight poison damage and loses two points of Constitution. Save modifier of -3.
21st level: Target suffers ten poison damage and loses three points of Constitution. Save modifier of -4.~

COPY_EXISTING ~C0DMM04.SPL~ OVERRIDE
SAY NAME1 ~Crushing Darkness~
SAY UNIDENTIFIED_DESC ~Crushing Darkness
The Dark Moon Monk unleashes ki in a wave of psychic energy that assaults all creatures within a 15-ft. radius with an overwhelming despair, dealing 10d6 magical damage and draining them of two levels. For each target slain by this ability, the Dark Moon Monk is healed for 15% of their maximum hit points and temporarily gains +2 to THAC0 and Damage for six rounds.~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0dmm04p.PRO~
COPY_EXISTING ~C0DMM04D.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0dmm04p END

COPY_EXISTING ~C0DMM05.SPL~ OVERRIDE
SAY NAME1 ~Eclipse~
SAY UNIDENTIFIED_DESC ~Eclipse
The Dark Moon Monk becomes wreathed in a cold shroud for one turn, gaining immunity to cold damage and +4 to Strength, Dexterity and Constitution. Any opponent who hits the Dark Moon Monk with any weapons or spells within this radius suffers 1d8+1 points of cold damage and must make a save vs. spells or be sapped, suffering an additional 1d6 magic damage and one point of THAC0 which is temporarily transferred to the Dark Moon Monk for two rounds.~

COPY_EXISTING ~C0SSM01.SPL~ OVERRIDE
SAY NAME1 ~Radiant Sunbolts~
SAY UNIDENTIFIED_DESC ~Radiant Sunbolts
The Sun Soul Monk can create bolts of energy that flare with radiant light. These bolts can be thrown as a projectile with a +5 bonus to attack rolls. Each bolt deals 1d4+1 points of magical damage and 3 extra points of magic fire damage (10 against undead) and strike as +4 weapons. The Sun Soul Monk produces 5 missiles (+1 additional bolt per 5 monk levels) and may hurl up to five missiles per round.~

COPY_EXISTING ~C0SSMBO1.SPL~ OVERRIDE
SAY NAME1 ~Radiant Sunbolts~
SAY NAME2 ~Radiant Sunbolts~

COPY_EXISTING ~C0SSM02.SPL~ OVERRIDE
SAY NAME1 ~Blazing Fists~
SAY UNIDENTIFIED_DESC ~Blazing Fists
The Sun Soul Monk channels their inner light into their unarmed attacks, turning their fists into flaming weapons that deal an additional 1d4 fire damage (+1 per point of Wisdom above 14) for 1 round per 5 levels.~

COPY_EXISTING ~C0SSM03.SPL~ OVERRIDE
SAY NAME1 ~Searing Arc Strike~
SAY UNIDENTIFIED_DESC ~Searing Arc Strike
The Sun Soul Monk gathers ki within their fists and shapes them into searing waves of white-hot flames. The monk's next successful melee attack unleashes a 140-degree cone of flame which deals 5d6 magical fire damage and severely burns all targets, reducing their Armor Class, THAC0 and Damage by 4 points and dealing an additional 1d6 fire damage per round for one turn unless a successful Save vs. Spells is made. Additionally, all invisible targets lose their invisibility with no save.~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0ssm04p.PRO~
COPY_EXISTING ~C0SSM04.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0ssm04p END
SAY NAME1 ~Searing Sunburst~
SAY UNIDENTIFIED_DESC ~Searing Sunburst
The Sun Soul Monk unleashes their ki in a massive pillar of light, dealing 10d6 magical damage to all enemies and blinding them for one round. Undead creatures must make a save vs. spells or be instantly destroyed.~

COPY_EXISTING ~C0SSM05.SPL~ OVERRIDE
SAY NAME1 ~Solar Shield~
SAY UNIDENTIFIED_DESC ~Solar Shield
The Sun Soul Monk becomes wreathed in a luminous mantle, gaining immunity to fire damage and dealing 30% increased fire damage from all sources for 1 turn. Any opponent who hits the Sun Soul Monk with any weapons or spells within this radius suffers 1d8+1 points of magical fire damage and must make a save vs. spells or take an additional 1d8 magical fire damage and be blinded for one round.~

INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//ITEMS

COPY_EXISTING ~C0MNRO01.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +1~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 6

Weight: 4~

COPY_EXISTING ~C0MNRO01.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +1~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 6

Weight: 4~

COPY_EXISTING ~C0MNRO02.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +2~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 5

Weight: 4~

COPY_EXISTING ~C0MNRO03.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +3~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 4

Weight: 4~

COPY_EXISTING ~C0MNRO04.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +4~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 3

Weight: 4~

COPY_EXISTING ~C0MNRO05.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +5~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 2

Weight: 4~

COPY_EXISTING ~C0MNRO06.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Old Order~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~Whatever the motives of the Monks of the Old Order might be, no one doubts that they are keenly, defensively minded. Rumor has it that the masters of the order attain ranks by being able to survive a beating by an Ogre, without ever raising a hand in defense. True or not, these robes, produced by the order to fund monasteries, are the trade mark of any monk who would survive in the frontlines of combat, against an enemy clad in armor.

Equipped abilities:
– Armor Class: +2
– Physical Resistance: +10%

Weight: 4~

COPY_EXISTING ~C0MNRO07.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Dark Moon~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~When she was a young student in the monastery of the Dark Moon monks, Beyl Van Yoren's teachers would constantly urge her to move faster and faster. They were finally appeased, when she suddenly began to be able to hit them four shots for every one of theirs. Despite her speed, Beyl found she had trouble concentrating on lessons, usually because she was moving so much faster than everyone else, that she would often grow bored and restless. Eventually she gave up the robes and the monastery to go and live with the wizard, whom she had traded 'personal favors' with for months, to earn the robes.

Equipped abilities:
– Haste
– Saving Throws: -1

Weight: 4~

COPY_EXISTING ~C0MNRO08.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Broken Ones~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~These bulky robes are worn by followers of Ilmater, god of endurance and martyrdom. Monks of the Order of the Broken Ones follow a code of selflessness, raising their fists to defend the innocents rather than deal harm to others. These robes are reflective of their pacifistic ideology, designed to protect its wearer from danger.

Equipped abilities:
– Armor Class: +4
– Saving Throws: +2
– Maximum Hit Points: +30
– THAC0: -2
– Immunity to Poison

Weight: 4~

COPY_EXISTING ~C0MNRO09.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Inner Eye~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~Yang Xun, a Shou martial artist, was a gifted student of the Heavenly Dragon school whose talent led him to be scouted for a respected position in the Emperor's personal guard. Unfortunately, his sibling students, envious of his potential, conspired to cut his future short by poisoning his wine with a toxin that rendered him nearly blind and unable to continue his training. His master, unwilling to see his talented pupil's life wasted, brought him to a monastery to be cared for by the esteemed abbot, his closest friend. Five years later, Yang made the journey back to his school to visit his former master where his rivals, fearful of retribution, attempted to ambush him en route under the cover of darkness, only for a blindfolded Yang to effortlessly dodge their blades, spears and knives as though possessing a sixth sense, until all his opponents lay broken and defeated, without a single stain or tear on Yang's initiate robes.

Equipped abilities:
– Armor Class: +2 vs. slashing and piercing attacks
– Protects against critical hits

Weight: 4~

COPY_EXISTING ~C0MNBR01.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +1~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +1
– Unarmed attacks strike as +1 weapons and deal 1 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR02.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +2~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +2
– Unarmed attacks strike as +2 weapons and deal 2 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR03.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +3~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +3
– Unarmed attacks strike as +3 weapons and deal 3 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR04.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +1~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +1
– Unarmed attacks strike as +1 weapons and deal 1 additional cold damage

Weight: 2~

COPY_EXISTING ~C0MNBR05.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +2~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +2
– Unarmed attacks strike as +2 weapons and deal 2 additional cold damage

Weight: 2~

COPY_EXISTING ~C0MNBR06.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +3~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +3
– Unarmed attacks strike as +3 weapons and deal 3 additional cold damage

Weight: 2~

ACTION_IF FILE_EXISTS_IN_GAME ~tem3402.sto~ THEN BEGIN
COPY_EXISTING ~tem3402.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~stoblack.sto~ THEN BEGIN
COPY_EXISTING ~stoblack.sto~ ~override~
ADD_STORE_ITEM ~c0mnbr05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~AR5001.ARE~ BEGIN
    COPY_EXISTING ~AR5001.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 1
      STR_VAR
        item_to_add = ~c0mnbr04~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~AR2615.ARE~ BEGIN
    COPY_EXISTING ~AR2615.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 2
      STR_VAR
        item_to_add = ~c0mnbr02~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~tem4802.sto~ THEN BEGIN
COPY_EXISTING ~tem4802.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~taerum.sto~ THEN BEGIN
COPY_EXISTING ~taerum.sto~ ~override~
ADD_STORE_ITEM ~c0mnro09~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdkazzre.sto~ THEN BEGIN
COPY_EXISTING ~bdkazzre.sto~ ~override~
ADD_STORE_ITEM ~c0mnro05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bddosia.sto~ THEN BEGIN
COPY_EXISTING ~bddosia.sto~ ~override~
ADD_STORE_ITEM ~c0mnro08~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbeleg4.sto~ THEN BEGIN
COPY_EXISTING ~bdbeleg4.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr04~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdinsa06.cre~ THEN BEGIN
COPY_EXISTING ~bdinsa06.cre~ ~override~
ADD_CRE_ITEM ~c0mnbr03~ #0 #0 #0 ~NONE~ ~GLOVES~
END

ACTION_IF GAME_INCLUDES ~SOD~ THEN BEGIN
COPY ~%MOD_FOLDER%/MonkRevision/creatures/C0MNEV01.cre~ ~override~
SAY NAME1 ~Black Hand~
SAY NAME2 ~Black Hand~
COPY_EXISTING BD5300.are override
  LPF fj_are_structure
    INT_VAR
    fj_loc_x          = 1417
    fj_loc_y          = 1131
    fj_dest_x         = 1417
    fj_dest_y         = 1131
    fj_animation      = 0x6500 
    fj_orientation    = 0     
    STR_VAR
    fj_structure_type = actor
    fj_name           = Black Hand
    fj_cre_resref     = c0mnev01
  END
END

//// DARK MOON MONK SPELLCASTING

ACTION_IF FILE_EXISTS_IN_GAME ~EEex_Actionbar.lua~ THEN BEGIN
INCLUDE ~%MOD_FOLDER%/lib/replace_multiline.tpa~

COPY ~%MOD_FOLDER%/lua/m_c0dmm1.lua~      ~override~

COPY_EXISTING ~SPWI106.spl~ ~override/C0DM101.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI112.spl~ ~override/C0DM102.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI120.spl~ ~override/C0DM103.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI125.spl~ ~override/C0DM104.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI201.spl~ ~override/C0DM201.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI205.spl~ ~override/C0DM202.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI212.spl~ ~override/C0DM203.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI223.spl~ ~override/C0DM204.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI307.spl~ ~override/C0DM301.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI308.spl~ ~override/C0DM302.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI314.spl~ ~override/C0DM303.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI315.spl~ ~override/C0DM304.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI403.spl~ ~override/C0DM401.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI405.spl~ ~override/C0DM402.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI409.spl~ ~override/C0DM403.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI414.spl~ ~override/C0DM404.spl~
WRITE_SHORT 0x1C 3 

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//dark_moon
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "DARK_MOON" BEGIN
          READ_2DA_ENTRY index 4 col_count dark_moon_desc
          SPRINT old_dark_moon ~SORCEROUS LINEAGE: Disciples of the Order of the Dark Moon must display some sort of sorcerous power during their initiation. As such, All Dark Moon Monks have a minor level of magical ability. This ability allows the Dark Moon Monk to cast a level 1 Invocation, Illusion or Necromancy spell of choice once per day. As the Dark Moon Monk gains in levels, stronger spells may be chosen, gaining level 2 spells at 5th level, level 3 spells at 9th level, level 4 spells at 13th level and level 5 spells at 17th level.~
          SPRINT new_dark_moon ~SORCEROUS LINEAGE: Disciples of the Order of the Dark Moon must display some sort of sorcerous power during their initiation. As such, All Dark Moon Monks have a minor level of magical ability, giving them the ability to cast a limited selection of spells of the Invocation, Illusion and Necromancy schools as a mage would. The Dark Moon Monk gains more powerful spells as they level up, gaining level 2 spells at 5th level, level 3 spells at 9th level and level 4 spells at 13th level. The spells learned are as follows:
  Level 1: Blindness, Magic Missile, Reflected Image, Spook
  Level 2: Blur, Mirror Image, Horror, Deafness
  Level 3: Invisibility 10' Radius, Lightning Bolt, Vampiric Touch, Wraithform
  Level 4: Fireshield (Blue), Improved Invisibility, Contagion, Spirit Armor~
          GET_STRREF %dark_moon_desc% dark_moon_text
          INNER_PATCH_SAVE dark_moon_text ~%dark_moon_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_dark_moon%~ ~%new_dark_moon%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%dark_moon_desc%~ ~%dark_moon_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  
ACTION_IF FILE_EXISTS_IN_GAME ~CLABMO02.2DA~ BEGIN
COPY_EXISTING ~CLABMO02.2DA~ ~OVERRIDE~
  REPLACE_TEXTUALLY ~GA_C0DMM01~ ~****      ~
COPY_EXISTING ~CLABMO02.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM101 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM102 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM103 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM104 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM201 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM202 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM203 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM204 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM301 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM302 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM303 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM304 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM401 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM402 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM403 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM404 END
  PRETTY_PRINT_2DA
BUT_ONLY
END
END
