IF
	Global("BDAI_INIT_ATTACK","LOCALS",0)
	!Global("BDAI_ATTACK_MODE","LOCALS",2)
	OR(6)
		Kit(Myself,FERALAN)
		CheckStatGT(Myself,2,PROFICIENCYCROSSBOW)
		CheckStatGT(Myself,2,PROFICIENCYLONGBOW)
		CheckStatGT(Myself,2,PROFICIENCYSHORTBOW)
		CheckStatGT(Myself,2,PROFICIENCYDART)
		CheckStatGT(Myself,2,PROFICIENCYSLING)
THEN
	RESPONSE #100
		SetGlobal("BDAI_INIT_ATTACK","LOCALS",1)
		SetGlobal("BDAI_ATTACK_MODE","LOCALS",2)
		Continue()
END

IF
	Global("BDAI_ATTACK_MODE","LOCALS",1)
	ActionListEmpty()
	IsWeaponRanged(Myself)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	Global("BDAI_ATTACK_MODE","LOCALS",2)
	ActionListEmpty()
	IsWeaponRanged(Myself)
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	Global("BDAI_ATTACK_MODE","LOCALS",2)
	ActionListEmpty()
	!IsWeaponRanged(Myself)
	CanEquipRanged()
	!Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		Continue()
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HaveSpellRES("SPIN102")  // Slow Poison
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",Myself)  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT([EVILCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([EVILCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
	!CheckStat(Myself,1,PUPPETTYPE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SANCTUARY)  // SPPR109.SPL (Sanctuary)
	!StateCheck(Myself,STATE_INVISIBLE)
	!CheckStat(Myself,1,SANCTUARY)
	HPPercentLT(Myself,51)
	!CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_SANCTUARY)  // SPPR109.SPL (Sanctuary)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(CLERIC_IRONSKIN)  // SPPR506.SPL (Iron Skins)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_IRONSKIN)  // SPPR506.SPL (Iron Skins)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,81)
	HaveSpell(PALADIN_LAY_ON_HANDS)  // SPCL211.SPL (Lay On Hands)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,PALADIN_LAY_ON_HANDS)  // SPCL211.SPL (Lay On Hands)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,81)
	HaveSpell(MONK_LAY_ON_HANDS)  // SPCL815.SPL (Lay On Hands)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,MONK_LAY_ON_HANDS)  // SPCL815.SPL (Lay On Hands)
END

IF
	Global("BDAI_DISABLE_ITEMS","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,70)
	HasItem("POTN55",Myself)  // Potion of Superior Healing
	ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		UseItem("POTN55",Myself)  // Potion of Superior Healing
		DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
	Global("BDAI_DISABLE_ITEMS","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,85)
	HasItem("POTN52",Myself)  // Potion of Extra Healing
	ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		UseItem("POTN52",Myself)  // Potion of Extra Healing
		DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
	Global("BDAI_DISABLE_ITEMS","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,85)
	HasItem("POTN08",Myself)  // Potion of Healing
	ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		UseItem("POTN08",Myself)  // Potion of Healing
		DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
	Global("BDAI_DISABLE_ITEMS","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,85)
	HasItem("POTN17",Myself)  // Elixir of Health
	ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		UseItem("POTN17",Myself)  // Elixir of Health
		DisplayString(Myself,46150)  // *quaffs a potion*
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast([EVILCUTOFF.0.0.MAGE_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([EVILCUTOFF.0.0.MAGE_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([EVILCUTOFF.0.0.MAGE_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([EVILCUTOFF.0.0.MAGE_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([EVILCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([EVILCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([EVILCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([EVILCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([EVILCUTOFF.0.0.SHAMAN],CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SecondNearest([EVILCUTOFF.0.0.SHAMAN]),CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(ThirdNearest([EVILCUTOFF.0.0.SHAMAN]),CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FourthNearest([EVILCUTOFF.0.0.SHAMAN]),CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FifthNearest([EVILCUTOFF.0.0.SHAMAN]),CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	ActionListEmpty()
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",0)
	OR(9)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SixthNearest([EVILCUTOFF.0.0.SHAMAN]),CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",1)
		SetGlobalTimer("BD_CLTM","LOCALS",60)
		Continue()
END

IF
	Global("BD_Cloud","LOCALS",1)
	GlobalTimerExpired("BD_CLTM","LOCALS")
	ActionListEmpty()
THEN
	RESPONSE #100
		SetGlobal("BD_Cloud","LOCALS",0)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
	Global("BD_Cloud","LOCALS",1)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobal("BD_Cloud","LOCALS",0)
		Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(PALADIN_PROTECTION_FROM_EVIL)  // SPCL213.SPL (Protection From Evil)
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,PALADIN_PROTECTION_FROM_EVIL)  // SPCL213.SPL (Protection From Evil)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
	Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	OR(2)
		CheckStat([GOODCUTOFF],0,PROTECTION_FROM_EVIL)
		CheckStat(SecondNearest([GOODCUTOFF]),0,PROTECTION_FROM_EVIL)
	OR(2)
		Range([GOODCUTOFF],12)
		Range(SecondNearest([GOODCUTOFF]),12)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	HaveSpell(BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,BERSERKER_RAGE)  // SPCL321.SPL (Enrage)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	HaveSpell(BARBARIAN_RAGE)  // SPCL152.SPL (Barbarian Rage)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,BARBARIAN_RAGE)  // SPCL152.SPL (Barbarian Rage)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See([GOODCUTOFF])
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,WEB)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(SecondNearest([GOODCUTOFF]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,WEB)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(ThirdNearest([GOODCUTOFF]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,WEB)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(FourthNearest([GOODCUTOFF]))
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,WEB)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,WEB)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	!GlobalTimerNotExpired("BD_RParal","LOCALS")
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,WEB)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_RParal","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck([GOODCUTOFF],STATE_PANIC)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(SecondNearest([GOODCUTOFF]),STATE_PANIC)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(ThirdNearest([GOODCUTOFF]),STATE_PANIC)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(FourthNearest([GOODCUTOFF]),STATE_PANIC)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(FifthNearest([GOODCUTOFF]),STATE_PANIC)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	StateCheck(SixthNearest([GOODCUTOFF]),STATE_PANIC)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player1)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player2)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player3)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player4)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player5)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_SCLAR","LOCALS")
	See(Player6)
	OR(4)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_SCLAR","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_CLARITY)  // SPPR350.SPL (Spiritual Clarity)
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See(FourthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See(FifthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN102")  // Slow Poison
	See(SixthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	OR(2)
		Range(LastSeenBy(Myself),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN102",LastSeenBy(Myself))  // Slow Poison
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See([PC])
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See(SecondNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See(ThirdNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See(FourthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See(FifthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
	See(SixthNearest([PC]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	CheckStatGT(Myself,0,LEVELDRAIN)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	CheckStatGT(Myself,0,LEVELDRAIN)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_LESSER_RESTORATION)  // SPPR417.SPL (Lesser Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See([PC])
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(SecondNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(FourthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(FifthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	See(SixthNearest([PC]))
	CheckStatGT(LastSeenBy(Myself),0,LEVELDRAIN)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	Global("BD_DInv","LOCALS",0)
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	OR(6)
		SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(SecondNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(ThirdNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(FourthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(FifthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(SixthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",1)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	Global("BD_DInv","LOCALS",1)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	ActuallyInCombat()
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See([EVILCUTOFF.0.0.0.0.ILLUSIONARY])
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(NearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(SecondNearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(ThirdNearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(FourthNearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(FifthNearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
	See(SixthNearestEnemyOf(Myself))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		Gender(LastSeenBy(Myself),ILLUSIONARY)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,INQUIS_TRUE_SIGHT)  // SPCL232.SPL (True Sight)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	OR(2)
		HPPercentLT(Myself,51)
		HPPercentLT([PC],51)
	OR(2)
		HPPercentLT(SecondNearest([PC]),51)
		HPPercentLT(ThirdNearest([PC]),51)
	OR(2)
		Range([PC],12)
		Range(SecondNearest([PC]),12)
	OR(2)
		Range(ThirdNearest([PC]),12)
		HPPercentLT(Myself,51)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CURE_CRITICAL_WOUNDS)  // SPPR502.SPL (Cure Critical Wounds)
	See(MostDamagedOf([PC]))
	HPPercentLT(LastSeenBy(Myself),40)
	InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CURE_CRITICAL_WOUNDS)  // SPPR502.SPL (Cure Critical Wounds)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Cure Serious Wounds)
	See(MostDamagedOf([PC]))
	HPPercentLT(LastSeenBy(Myself),40)
	InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CURE_SERIOUS_WOUNDS)  // SPPR401.SPL (Cure Serious Wounds)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
	See(MostDamagedOf([PC]))
	HPPercentLT(LastSeenBy(Myself),40)
	InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)  // SPPR315.SPL (Cure Medium Wounds)
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN101")  // Cure Light Wounds
	See(MostDamagedOf([PC]))
	HPPercentLT(LastSeenBy(Myself),40)
	InParty(LastSeenBy(Myself))
	OR(2)
		Range(MostDamagedOf([PC]),6)
		!Range(NearestEnemyOf(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN101",LastSeenBy(Myself))  // Cure Light Wounds
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
	See(MostDamagedOf([PC]))
	HPPercentLT(LastSeenBy(Myself),40)
	InParty(LastSeenBy(Myself)) 	
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)  // SPPR103.SPL (Cure Light Wounds)
		SetInterrupt(TRUE)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
	IsWeaponRanged(Myself)
	!Range([EVILCUTOFF],5)
	OR(4)
		CheckStatGT([EVILCUTOFF],12,LEVEL)
		CheckStatGT(SecondNearest([EVILCUTOFF]),12,LEVEL)
		CheckStatGT(ThirdNearest([EVILCUTOFF]),12,LEVEL)
		NumCreatureGT([EVILCUTOFF],4)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,ARCHER_CALL_SHOT)  // SPCL121.SPL (Called Shot)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
	StateCheck(Player2,STATE_REALLY_DEAD)
	InPartyAllowDead(Player2)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player2,CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
	StateCheck(Player3,STATE_REALLY_DEAD)
	InPartyAllowDead(Player3)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player3,CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
	StateCheck(Player4,STATE_REALLY_DEAD)
	InPartyAllowDead(Player4)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player4,CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
	StateCheck(Player5,STATE_REALLY_DEAD)
	InPartyAllowDead(Player5)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player5,CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
	StateCheck(Player6,STATE_REALLY_DEAD)
	InPartyAllowDead(Player6)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player6,CLERIC_RAISE_DEAD)  // SPPR504.SPL (Raise Dead)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
	StateCheck(Player2,STATE_REALLY_DEAD)
	InPartyAllowDead(Player2)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player2,CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
	StateCheck(Player3,STATE_REALLY_DEAD)
	InPartyAllowDead(Player3)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player3,CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
	StateCheck(Player4,STATE_REALLY_DEAD)
	InPartyAllowDead(Player4)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player4,CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
	StateCheck(Player5,STATE_REALLY_DEAD)
	InPartyAllowDead(Player5)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player5,CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
	StateCheck(Player6,STATE_REALLY_DEAD)
	InPartyAllowDead(Player6)
	CombatCounter(0)
	!Range([EVILCUTOFF],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Player6,CLERIC_RECALL_SPIRIT)  // SPPR550.SPL (Recall Spirit)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_ARMOR)  // SPWI102.SPL (Armor)
	CheckStatGT(Myself,6,ARMORCLASS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_ARMOR)  // SPWI102.SPL (Armor)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Dharm","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
	NumCreatureGT([EVILCUTOFF],3)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStat(Myself,0,CLERIC_DEFENSIVE_HARMONY)
	Range([EVILCUTOFF],30)
	Range([GOODCUTOFF],12)
	Range(SecondNearest([GOODCUTOFF]),12)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Dharm","LOCALS",18)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY)  // SPPR406.SPL (Defensive Harmony)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
	See([EVILCUTOFF])
	OR(2)
		CheckStatGT(LastSeenBy(Myself),12,LEVEL)
		NumCreatureGT([EVILCUTOFF],3)
	!CheckSpellState(Myself,ARMOR_OF_FAITH)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpellRES("SPIN103")  // Draw Upon Holy Might
	See([EVILCUTOFF])
	OR(2)
		CheckStatGT(LastSeenBy(Myself),12,LEVEL)
		NumCreatureGT([EVILCUTOFF],3)
	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN103",Myself)  // Draw Upon Holy Might
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
	See([EVILCUTOFF])
	OR(2)
		CheckStatGT(LastSeenBy(Myself),12,LEVEL)
		NumCreatureGT([EVILCUTOFF],3)
	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,51)
	HaveSpellRES("SPIN106")  // Vampiric Touch
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SALAMANDER)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),SWORD)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN106",NearestEnemyOf(Myself))  // Vampiric Touch
		SetInterrupt(FALSE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
	NumCreatureGT([EVILCUTOFF],3)
	See([EVILCUTOFF])
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),TROLL)
	!Race(LastSeenBy(Myself),SLIME)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF],WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
	NumCreatureGT([EVILCUTOFF],3)
	See(SecondNearest([EVILCUTOFF]))
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),TROLL)
	!Race(LastSeenBy(Myself),SLIME)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF]),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
	NumCreatureGT([EVILCUTOFF],3)
	See(ThirdNearest([EVILCUTOFF]))
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),TROLL)
	!Race(LastSeenBy(Myself),SLIME)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF]),WIZARD_CONFUSION)  // SPWI401.SPL (Confusion)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat([EVILCUTOFF.0.TROLL],100,RESISTSLASHING)
	See([EVILCUTOFF.0.TROLL])
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.0.TROLL],WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat(SecondNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SecondNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.0.TROLL]),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(ThirdNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF.0.TROLL]),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat(FourthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FourthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FourthNearest([EVILCUTOFF.0.TROLL]),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat(FifthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FifthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FifthNearest([EVILCUTOFF.0.TROLL]),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	CheckStat(SixthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SixthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SixthNearest([EVILCUTOFF.0.TROLL]),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	See(NearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	See(SecondNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearestEnemyOf(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
	See(ThirdNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearestEnemyOf(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat([EVILCUTOFF.0.TROLL],100,RESISTSLASHING)
	See([EVILCUTOFF.0.TROLL])
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.0.TROLL],WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat(SecondNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SecondNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.0.TROLL]),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(ThirdNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF.0.TROLL]),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat(FourthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FourthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FourthNearest([EVILCUTOFF.0.TROLL]),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat(FifthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FifthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FifthNearest([EVILCUTOFF.0.TROLL]),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
	CheckStat(SixthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SixthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),8)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SixthNearest([EVILCUTOFF.0.TROLL]),WIZARD_BURNING_HANDS)  // SPWI103.SPL (Burning Hands)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat([EVILCUTOFF.0.TROLL],100,RESISTSLASHING)
	See([EVILCUTOFF.0.TROLL])
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.0.TROLL],WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat(SecondNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SecondNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.0.TROLL]),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(ThirdNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF.0.TROLL]),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat(FourthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FourthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FourthNearest([EVILCUTOFF.0.TROLL]),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat(FifthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FifthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(FifthNearest([EVILCUTOFF.0.TROLL]),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	CheckStat(SixthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SixthNearest([EVILCUTOFF.0.TROLL]))
	!InParty(LastSeenBy(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SixthNearest([EVILCUTOFF.0.TROLL]),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range([EVILCUTOFF.0.TROLL],30)
	CheckStat([EVILCUTOFF.0.TROLL],100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range(SecondNearest([EVILCUTOFF.0.TROLL]),30)
	CheckStat(SecondNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range(ThirdNearest([EVILCUTOFF.0.TROLL]),30)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range(FourthNearest([EVILCUTOFF.0.TROLL]),30)
	CheckStat(FourthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range(FifthNearest([EVILCUTOFF.0.TROLL]),30)
	CheckStat(FifthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	Range(SixthNearest([EVILCUTOFF.0.TROLL]),30)
	CheckStat(SixthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	!Range([EVILCUTOFF],8)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
	!HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	NumCreatureGT([EVILCUTOFF],3)
	!Range([EVILCUTOFF],8)
	CheckStatLT([EVILCUTOFF],76,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)  // SPWI325.SPL (Melf's Minute Meteors)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
	OR(4)
		See([EVILCUTOFF.0.0.MAGE_ALL])
		See([EVILCUTOFF.0.0.CLERIC_ALL])
		See([EVILCUTOFF.0.0.DRUID_ALL])
		See([EVILCUTOFF.0.0.BARD_ALL])
	CheckStat(Myself,0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)  // SPWI406.SPL (Minor Globe of Invulnerability)
END

IF
	ActionListEmpty()
	Global("BD_Shield","LOCALS",0)
	HaveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
	!CheckStat(Myself,2,DEFENSIVE_MODIFIER)
	CheckStat(Myself,0,MINORGLOBE)
	OR(11)
		SpellCast([EVILCUTOFF],WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(SecondNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(ThirdNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(FourthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(FifthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(SixthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(SeventhNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(EighthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(NinthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCast(TenthNearest([EVILCUTOFF]),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
		SpellCastOnMe([ANYONE],WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
THEN
	RESPONSE #100
		SetGlobal("BD_Shield","LOCALS",1)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
	Global("BD_Shield","LOCALS",1)
	!CheckStat(Myself,2,DEFENSIVE_MODIFIER)
	CheckStat(Myself,0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobal("BD_Shield","LOCALS",0)
		Spell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_SHIELD)  // SPWI114.SPL (Shield)
	OR(11)
		HitBy([ANYONE],MISSILE)
		IsWeaponRanged(NearestEnemyOf(Myself))
		IsWeaponRanged(SecondNearestEnemyOf(Myself))
		IsWeaponRanged(ThirdNearestEnemyOf(Myself))
		IsWeaponRanged(FourthNearestEnemyOf(Myself))
		IsWeaponRanged(FifthNearestEnemyOf(Myself))
		IsWeaponRanged(SixthNearestEnemyOf(Myself))
		IsWeaponRanged(SeventhNearestEnemyOf(Myself))
		IsWeaponRanged(EighthNearestEnemyOf(Myself))
		IsWeaponRanged(NinthNearestEnemyOf(Myself))
		IsWeaponRanged(TenthNearestEnemyOf(Myself))
	!CheckStat(Myself,2,DEFENSIVE_MODIFIER)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobal("BD_Shield","LOCALS",0)
		Spell(Myself,WIZARD_SHIELD)  // SPWI114.SPL (Shield)
END

IF
	ActionListEmpty()
	Global("BD_DInv","LOCALS",0)
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	OR(6)
		SpellCast([EVILCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(SecondNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(ThirdNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(FourthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(FifthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
		SpellCast(SixthNearest([EVILCUTOFF]),WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",1)
END

IF
	ActionListEmpty()
	Global("BD_DInv","LOCALS",1)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	ActuallyInCombat()
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Haste","LOCALS")
	HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
	NumCreatureGT([EVILCUTOFF],3)
	See([GOODCUTOFF.0.0.FIGHTER_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HASTED)
	CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Haste","LOCALS",18)
		Spell([GOODCUTOFF.0.0.FIGHTER_ALL],WIZARD_HASTE)  // SPWI305.SPL (Haste)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Haste","LOCALS")
	HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
	NumCreatureGT([EVILCUTOFF],3)
	See([GOODCUTOFF.0.0.RANGER_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HASTED)
	CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Haste","LOCALS",18)
		Spell([GOODCUTOFF.0.0.RANGER_ALL],WIZARD_HASTE)  // SPWI305.SPL (Haste)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Haste","LOCALS")
	HaveSpell(WIZARD_HASTE)  // SPWI305.SPL (Haste)
	NumCreatureGT([EVILCUTOFF],3)
	See([GOODCUTOFF.0.0.PALADIN_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HASTED)
	CheckStat(LastSeenBy(Myself),0,IMPROVEDHASTE)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Haste","LOCALS",18)
		Spell([GOODCUTOFF.0.0.PALADIN_ALL],WIZARD_HASTE)  // SPWI305.SPL (Haste)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(NearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(NearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(SecondNearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(ThirdNearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(FourthNearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(FifthNearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_DInv","LOCALS")
	HaveSpell(WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
	See(SixthNearestEnemyOf(Myself))
	StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_NONDETECTION)
	CheckStat(Myself,0,TRUE_SIGHT)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobal("BD_DInv","LOCALS",0)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_DInv","LOCALS",12)
		Spell(Myself,WIZARD_DETECT_INVISIBILITY)  // SPWI203.SPL (Detect Invisibility)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	NumCreatureGT([EVILCUTOFF],2)
	See(NearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Slow","LOCALS",18)
		Spell(NearestEnemyOf(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	NumCreatureGT([EVILCUTOFF],2)
	See(SecondNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Slow","LOCALS",18)
		Spell(SecondNearestEnemyOf(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Slow","LOCALS")
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	NumCreatureGT([EVILCUTOFF],2)
	See(ThirdNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Slow","LOCALS",18)
		Spell(ThirdNearestEnemyOf(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
	NumCreatureGT([EVILCUTOFF],2)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.HUMANOID],WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	NumCreatureGT([EVILCUTOFF],2)
	HaveSpell(WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.HUMANOID]),WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	NumCreatureGT([EVILCUTOFF],2)
	HaveSpell(WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
	See(ThirdNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-1,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF.HUMANOID]),WIZARD_HOLD_PERSON)  // SPWI306.SPL (Hold Person)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
	See([EVILCUTOFF.HUMANOID.0.FIGHTER])
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.HUMANOID.0.FIGHTER],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
	See(SecondNearest([EVILCUTOFF.HUMANOID.0.FIGHTER]))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.HUMANOID.0.FIGHTER]),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.HUMANOID],CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.HUMANOID]),CLERIC_MENTAL_DOMINATION)  // SPPR405.SPL (Mental Domination)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_CHANT)  // SPPR203.SPL (Chant)
	!StateCheck(Myself,STATE_CHANT)
	NumCreatureGT([EVILCUTOFF],3)
	Range([EVILCUTOFF],30)
	Range([GOODCUTOFF],12)
	Range(SecondNearest([GOODCUTOFF]),12)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_CHANT)  // SPPR203.SPL (Chant)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_BLESS)  // SPPR101.SPL (Bless)
	NumCreatureGT([EVILCUTOFF],3)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	Range([EVILCUTOFF],30)
	Range([GOODCUTOFF],15)
	Range(SecondNearest([GOODCUTOFF]),15)
	!StateCheck(Myself,STATE_BLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_BLESS)  // SPPR101.SPL (Bless)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
	NumCreatureGT([EVILCUTOFF],3)
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	OR(2)
		CheckStat([GOODCUTOFF],0,PROTECTION_FROM_EVIL)
		CheckStat(SecondNearest([GOODCUTOFF]),0,PROTECTION_FROM_EVIL)
	OR(2)
		Range([GOODCUTOFF],12)
		Range(SecondNearest([GOODCUTOFF]),12)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)  // SPPR408.SPL (Protection From Evil, 10' Radius)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(PALADIN_PROTECTION_FROM_EVIL)  // SPCL213.SPL (Protection From Evil)
	NumCreatureGT([EVILCUTOFF],3)
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,PALADIN_PROTECTION_FROM_EVIL)  // SPCL213.SPL (Protection From Evil)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
	NumCreatureGT([EVILCUTOFF],3)
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(Myself,CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
	NumCreatureGT([EVILCUTOFF],3)
	See([PC])
	CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
	NumCreatureGT([EVILCUTOFF],3)
	See(SecondNearest([PC]))
	CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
	NumCreatureGT([EVILCUTOFF],3)
	See(ThirdNearest([PC]))
	CheckStat(LastSeenBy(Myself),0,PROTECTION_FROM_EVIL)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	OR(7)
		Alignment([EVILCUTOFF],MASK_EVIL)
		Alignment(SecondNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(ThirdNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FourthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(FifthNearest([EVILCUTOFF]),MASK_EVIL)
		Alignment(SixthNearest([EVILCUTOFF]),MASK_EVIL)
		Range([0.0.DEMONIC.0.0.SUMMONED_DEMON],30)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_EVIL)  // SPPR107.SPL (Protection From Evil)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_Support","LOCALS")
	HaveSpell(CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
	NumCreatureGT([EVILCUTOFF],3)
	See(WorstAC([PC]))
	!CheckSpellState(WorstAC([PC]),BARKSKIN)
	CheckStatGT(WorstAC([PC]),4,ARMORCLASS)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SetGlobalTimer("BD_Support","LOCALS",12)
		Spell(WorstAC([PC]),CLERIC_BARKSKIN)  // SPPR202.SPL (Barkskin)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See(ThirdNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See(FourthNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See(FifthNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
	See(SixthNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),UNDEADHUNTER)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)  // SPPR208.SPL (Hold Person)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MONSTER_SUMMONING_2)  // SPWI407.SPL (Monster Summoning II)
	OR(2)
		NumCreatureGT([EVILCUTOFF],4)
		CheckStatGT([EVILCUTOFF],12,LEVEL)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(Myself,WIZARD_MONSTER_SUMMONING_2)  // SPWI407.SPL (Monster Summoning II)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),5,LEVEL)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL3)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),5,LEVEL)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL3)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See(ThirdNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	CheckStatLT(LastSeenBy(Myself),5,LEVEL)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),5,LEVEL3)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)  // SPPR102.SPL (Command)
	See(ThirdNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)  // SPPR102.SPL (Command)
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
	See([EVILCUTOFF.HUMANOID.0.FIGHTER])
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.HUMANOID.0.FIGHTER],CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
	See(SecondNearest([EVILCUTOFF.HUMANOID.0.FIGHTER]))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.HUMANOID.0.FIGHTER]),CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
	See([EVILCUTOFF.HUMANOID])
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell([EVILCUTOFF.HUMANOID],CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
	See(SecondNearest([EVILCUTOFF.HUMANOID]))
	!InParty(LastSeenBy(Myself))
	!Class(LastSeenBy(Myself),MONK)
	!Kit(LastSeenBy(Myself),INQUISITOR)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),3,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(Myself,50,SPELLFAILUREPRIEST)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.HUMANOID]),CLERIC_CHARM_PERSON)  // SPPR204.SPL (Charm Person or Mammal)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(NearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	ActionListEmpty()
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	Global("BDAI_NO_ARCANE","LOCALS",0)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),LICH)
	!Race(LastSeenBy(Myself),DEMILICH)
	!Race(LastSeenBy(Myself),RAKSHASA)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearestEnemyOf(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,71)
	HaveSpellRES("SPIN104")  // Larloch's Minor Drain
	See(NearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SALAMANDER)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),SWORD)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		SpellRES("SPIN104",NearestEnemyOf(Myself))  // Larloch's Minor Drain
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,71)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
	See(NearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SALAMANDER)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),SWORD)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
END

IF
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HPPercentLT(Myself,71)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
	See(SecondNearestEnemyOf(Myself))
	!InParty(LastSeenBy(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SALAMANDER)
	!Race(LastSeenBy(Myself),GOLEM)
	!Race(LastSeenBy(Myself),SWORD)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(RANGER_CHARM_ANIMAL)  // SPCL311.SPL (Charm Animal)
	!Range([NEUTRAL.0.0.INNOCENT],30)
	!Range([GOODBUTBLUE],30)
	See(SecondNearest([EVILCUTOFF.ANIMAL]))
	!Race(LastSeenBy(Myself),DEMONIC)
	Range(LastSeenBy(Myself),6)
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(SecondNearest([EVILCUTOFF.ANIMAL]),RANGER_CHARM_ANIMAL)  // SPCL311.SPL (Charm Animal)
END

IF
	Global("BDAI_DISABLE_SPECIAL","LOCALS",0)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(RANGER_CHARM_ANIMAL)  // SPCL311.SPL (Charm Animal)
	!Range([NEUTRAL.0.0.INNOCENT],30)
	!Range([GOODBUTBLUE],30)
	See(ThirdNearest([EVILCUTOFF.ANIMAL]))
	!Race(LastSeenBy(Myself),DEMONIC)
	Range(LastSeenBy(Myself),6)
	!Class(LastSeenBy(Myself),MONK)
	!Race(LastSeenBy(Myself),ELF)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",6)
		Spell(ThirdNearest([EVILCUTOFF.ANIMAL]),RANGER_CHARM_ANIMAL)  // SPCL311.SPL (Charm Animal)
END

IF
	Global("BDAI_SKILL_MODE","LOCALS",1)
	ActionListEmpty()
	!See([EVILCUTOFF])
	!ModalState(DETECTTRAPS)
	!ModalState(STEALTH)
	OR(3)
		Class(Myself,THIEF_ALL)
		Class(Myself,MONK)
		Class(Myself,SHAMAN)
THEN
	RESPONSE #100
		FindTraps()
END

IF
	Global("BDAI_SKILL_MODE","LOCALS",2)
	ActionListEmpty()
	!GlobalTimerNotExpired("BD_HIDE","LOCALS")
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_BLIND)
	!ModalState(STEALTH)
	!Range(NearestEnemyOf(Myself),30)
	!ButtonDisabled(BUTTON_STEALTH)
	OR(3)
		Class(Myself,THIEF_ALL)
		Class(Myself,RANGER_ALL)
		Class(Myself,MONK)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_HIDE","LOCALS",6)
		Hide()
END

IF
	Global("BDAI_SKILL_MODE","LOCALS",3)
	ActionListEmpty()
	!ModalState(BATTLESONG)
	OR(2)
		Class(Myself,BARD_ALL)
		Class(Myself,SHAMAN)
	OR(2)
		Range([EVILCUTOFF],30)
		ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("BD_BRDS","LOCALS",1)
		BattleSong()
END

IF
	Global("BDAI_SKILL_MODE","LOCALS",3)
	ActionListEmpty()
	ModalState(BATTLESONG)
	!See([EVILCUTOFF])
	!ActuallyInCombat()
	OR(2)
		Class(Myself,BARD_ALL)
		Class(Myself,SHAMAN)
	Delay(30)
	Global("BD_BRDS","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("BD_BRDS","LOCALS",0)
		ClearActions(Myself)
END

IF
	Global("BDAI_SKILL_MODE","LOCALS",4)
	ActionListEmpty()
	!ModalState(TURNUNDEAD)
	Range([EVILCUTOFF.UNDEAD],12)
	OR(2)
		CanTurn([EVILCUTOFF.UNDEAD],5)
		CanTurn(SecondNearest([EVILCUTOFF.UNDEAD]),5)
	OR(2)
		CanTurn(ThirdNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(FourthNearest([EVILCUTOFF.UNDEAD]),5)
	OR(2)
		CanTurn(FifthNearest([EVILCUTOFF.UNDEAD]),5)
		CanTurn(SixthNearest([EVILCUTOFF.UNDEAD]),5)
	!ButtonDisabled(BUTTON_TURNUNDEAD)
THEN
	RESPONSE #100
		Turn()
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat([EVILCUTOFF.0.TROLL],100,RESISTSLASHING)
	See([EVILCUTOFF.0.TROLL])
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck([EVILCUTOFF.0.TROLL],STATE_REALLY_DEAD)
	!Allegiance([EVILCUTOFF.0.TROLL],GOODCUTOFF)
	!InParty([EVILCUTOFF.0.TROLL])
THEN
	RESPONSE #100
		AttackOneRound([EVILCUTOFF.0.TROLL])
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(ThirdNearest([EVILCUTOFF.0.TROLL]))
	!StateCheck(ThirdNearest([EVILCUTOFF.0.TROLL]),STATE_REALLY_DEAD)
	!Allegiance(ThirdNearest([EVILCUTOFF.0.TROLL]),GOODCUTOFF)
	!InParty(ThirdNearest([EVILCUTOFF.0.TROLL]))
THEN
	RESPONSE #100
		AttackOneRound(SecondNearest([EVILCUTOFF.0.TROLL]))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(ThirdNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(ThirdNearest([EVILCUTOFF.0.TROLL]))
	!StateCheck(ThirdNearest([EVILCUTOFF.0.TROLL]),STATE_REALLY_DEAD)
	!Allegiance(ThirdNearest([EVILCUTOFF.0.TROLL]),GOODCUTOFF)
	!InParty(ThirdNearest([EVILCUTOFF.0.TROLL]))
THEN
	RESPONSE #100
		AttackOneRound(ThirdNearest([EVILCUTOFF.0.TROLL]))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(FourthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FourthNearest([EVILCUTOFF.0.TROLL]))
	!StateCheck(FourthNearest([EVILCUTOFF.0.TROLL]),STATE_REALLY_DEAD)
	!Allegiance(FourthNearest([EVILCUTOFF.0.TROLL]),GOODCUTOFF)
	!InParty(FourthNearest([EVILCUTOFF.0.TROLL]))
THEN
	RESPONSE #100
		AttackOneRound(FourthNearest([EVILCUTOFF.0.TROLL]))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(FifthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(FifthNearest([EVILCUTOFF.0.TROLL]))
	!StateCheck(FifthNearest([EVILCUTOFF.0.TROLL]),STATE_REALLY_DEAD)
	!Allegiance(FifthNearest([EVILCUTOFF.0.TROLL]),GOODCUTOFF)
	!InParty(FifthNearest([EVILCUTOFF.0.TROLL]))
THEN
	RESPONSE #100
		AttackOneRound(FifthNearest([EVILCUTOFF.0.TROLL]))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	HasItem("MELFMET",Myself)  // Melf's Minute Meteor
	!StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(SixthNearest([EVILCUTOFF.0.TROLL]),100,RESISTSLASHING)
	See(SixthNearest([EVILCUTOFF.0.TROLL]))
	!StateCheck(SixthNearest([EVILCUTOFF.0.TROLL]),STATE_REALLY_DEAD)
	!Allegiance(SixthNearest([EVILCUTOFF.0.TROLL]),GOODCUTOFF)
	!InParty(SixthNearest([EVILCUTOFF.0.TROLL]))
THEN
	RESPONSE #100
		AttackOneRound(SixthNearest([EVILCUTOFF.0.TROLL]))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	CheckStat(Myself,0,SANCTUARY)
	WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
	See(NearestEnemyOf(Myself))
	!StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
	!Allegiance(NearestEnemyOf(Myself),GOODCUTOFF)
	!InParty(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	CheckStat(Myself,0,SANCTUARY)
	WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	!Allegiance(SecondNearestEnemyOf(Myself),GOODCUTOFF)
	!InParty(SecondNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
	!ModalState(BATTLESONG)
	Global("BDAI_DISABLE_ATTACK","LOCALS",0)
	ActionListEmpty()
	CheckStat(Myself,0,SANCTUARY)
	WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
	!Allegiance(ThirdNearestEnemyOf(Myself),GOODCUTOFF)
	!InParty(ThirdNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(ThirdNearestEnemyOf(Myself))
END
