
ACTION_IF NOT FILE_EXISTS_IN_GAME ~c0ekcc.spl~ BEGIN

COPY ~%MOD_FOLDER%/effects/combat_casting~ ~override~

ADD_PROJECTILE ~%MOD_FOLDER%/effects/combat_casting/c0ekccp.PRO~ ~Combat Casting~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

COPY_EXISTING ~c0ekcci1.bam~ ~override/c0ekcci2.bam~

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Combat Casting~) STR_VAR bam_file = c0ekcci1 RET c0ekcci1 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Improved Combat Casting~) STR_VAR bam_file = c0ekcci2 RET c0ekcci2 = icon END

COPY ~%MOD_FOLDER%/effects/combat_casting/c0ekcc1.spl~ ~override~
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = c0ekccp
END

COPY ~%MOD_FOLDER%/effects/combat_casting/c0ekcc1a.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ekcci1 END

COPY ~%MOD_FOLDER%/effects/combat_casting/c0ekcc1b.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ekcci2 END

END