- name: Automatic Releases
  # You may pin to the exact commit or the version.
  # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
  uses: marvinpinto/action-automatic-releases@v1.2.1
  with:
    # GitHub secret token
    repo_token: 
    # Git tag (for automatic releases)
    automatic_release_tag: # optional
    # Should this release be marked as a draft?
    draft: # optional
    # Should this release be marked as a pre-release?
    prerelease: # optional, default is true
    # Release title (for automatic releases)
    title: # optional
    # Assets to upload to the release
    files: # optional
